//! Server-side mute state, mirroring upstream `VoiceMuteManager` + its `JsonMuteStorage`.
//!
//! Upstream keeps a `Map<UUID, ServerMuteInfo>` of permanent/temporary server mutes
//! and persists them to `plugins/PlasmoVoice/mutes.json`. This module is the Rust
//! equivalent: a small process-wide store that the `vmute` / `vunmute` / `vmutelist`
//! commands mutate and the data plane (`relay_audio`) and control plane
//! (`voice_player_info`) read.
//!
//! ## Persistence
//!
//! The store is written as a flat TOML table (`mutes.toml` in the plugin's private
//! data folder) so it reuses [`crate::state::parse_flat_table`]:
//!
//! ```toml
//! # auto-generated by PlasmoPumpkin; muted_to_ms = 0 means the mute never expires.
//! mutes.<player-uuid>.muted_at_ms = 1700000000000
//! mutes.<player-uuid>.muted_to_ms = 0
//! mutes.<player-uuid>.muted_by = "<op-uuid>"
//! mutes.<player-uuid>.reason = "spamming"
//! ```
//!
//! Timestamps are Unix epoch milliseconds, matching [`crate::server::now_ms`] so a
//! single clock drives both the packet layer and the mute expiry check.
//!
//! The store is deliberately not part of `VoiceServer`: it is server-wide state the
//! commands and the protocol both reach through a process-global `OnceLock`, so a host
//! build (no WASI) that never calls [`init`] simply sees no mutes.

use std::collections::BTreeMap;
use std::sync::{Mutex, MutexGuard, OnceLock};

use uuid::Uuid;

use crate::state::{escape_toml, parse_flat_table, unquote};

/// File name of the mute table inside the plugin data folder.
pub const MUTE_FILE: &str = "mutes.toml";

/// One server mute, mirroring upstream `ServerMuteInfo`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ServerMute {
    /// The muted player.
    pub player_id: Uuid,
    /// Who issued the mute (`None` for a console/unknown issuer).
    pub muted_by: Option<Uuid>,
    /// Epoch millis when the mute was created.
    pub muted_at_ms: u64,
    /// Epoch millis when the mute lifts, or `0` for a permanent mute.
    pub muted_to_ms: u64,
    /// Optional human reason.
    pub reason: Option<String>,
}

impl ServerMute {
    /// Whether the mute is in force at `now` (epoch millis).
    ///
    /// `0` (permanent) minus a tie at an expiry instant: upstream treats
    /// `System.currentTimeMillis() < mutedToTime` as *still* muted, so a mute is
    /// valid up to but excluding its expiry instant.
    #[must_use]
    pub fn is_active(&self, now_ms: u64) -> bool {
        self.muted_to_ms == 0 || now_ms < self.muted_to_ms
    }

    /// A human-readable expiry suffix for command feedback.
    #[must_use]
    pub fn describe(&self, now_ms: u64) -> String {
        if self.muted_to_ms == 0 {
            "permanently".to_string()
        } else {
            let remaining = self.muted_to_ms.saturating_sub(now_ms) / 1000;
            format!("for {remaining}s")
        }
    }
}

/// The persistent mute table, keyed by the muted player.
#[derive(Debug, Default, Clone, PartialEq, Eq)]
pub struct MuteStore {
    mutes: BTreeMap<Uuid, ServerMute>,
}

impl MuteStore {
    /// Creates an empty store.
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// Parses a `mutes.toml` body. Malformed entries are skipped rather than
    /// rejected as a whole, so a hand-edited file degrades gracefully.
    pub fn load(text: &str) -> Result<Self, String> {
        let flat = parse_flat_table(text)?;
        let mut grouped: BTreeMap<Uuid, BTreeMap<String, String>> = BTreeMap::new();

        for (key, raw) in &flat {
            let Some(rest) = key.strip_prefix("mutes.") else {
                continue;
            };
            let Some((player, field)) = rest.split_once('.') else {
                continue;
            };
            let Ok(player_id) = Uuid::parse_str(player) else {
                continue;
            };
            grouped
                .entry(player_id)
                .or_default()
                .insert(field.to_string(), raw.clone());
        }

        let mut mutes = BTreeMap::new();
        for (&player_id, fields) in &grouped {
            let Some(muted_at_raw) = fields.get("muted_at_ms") else {
                continue;
            };
            let Ok(muted_at_ms) = muted_at_raw.parse::<u64>() else {
                continue;
            };
            let muted_to_ms = fields
                .get("muted_to_ms")
                .and_then(|v| v.parse::<u64>().ok())
                .unwrap_or(0);
            let muted_by = fields
                .get("muted_by")
                .map(|v| unquote(v))
                .filter(|s| !s.is_empty())
                .and_then(|s| Uuid::parse_str(&s).ok());
            let reason = fields
                .get("reason")
                .map(|v| unquote(v))
                .filter(|s| !s.is_empty());

            mutes.insert(
                player_id,
                ServerMute {
                    player_id,
                    muted_by,
                    muted_at_ms,
                    muted_to_ms,
                    reason,
                },
            );
        }

        Ok(Self { mutes })
    }

    /// Serializes the store as the flat TOML the [`Self::load`] reader expects.
    #[must_use]
    pub fn to_toml(&self) -> String {
        let mut out = String::from(
            "# auto-generated by PlasmoPumpkin — the persisted voice server mutes.\n\
             # muted_to_ms = 0 means the mute never expires; times are epoch millis.\n",
        );
        for mute in self.mutes.values() {
            let key = format!("mutes.{}", mute.player_id);
            out.push_str(&format!(
                "{key}.player_id = \"{}\"\n",
                escape_toml(&mute.player_id.to_string())
            ));
            if let Some(by) = mute.muted_by {
                out.push_str(&format!(
                    "{key}.muted_by = \"{}\"\n",
                    escape_toml(&by.to_string())
                ));
            }
            out.push_str(&format!("{key}.muted_at_ms = {}\n", mute.muted_at_ms));
            out.push_str(&format!("{key}.muted_to_ms = {}\n", mute.muted_to_ms));
            if let Some(reason) = &mute.reason {
                out.push_str(&format!("{key}.reason = \"{}\"\n", escape_toml(reason)));
            }
        }
        out
    }

    /// Writes the store to `folder/mutes.toml`, dropping expired entries first.
    pub fn save(&self, folder: &str) -> Result<(), String> {
        // Expiry is only observable here (or via an explicit purge); keeping the
        // on-disk file tidy is the one place it costs anything.
        let mut purged = self.clone();
        purged.purge_owned(crate::server::now_ms());
        std::fs::write(format!("{folder}/{MUTE_FILE}"), purged.to_toml())
            .map_err(|e| format!("cannot write {MUTE_FILE}: {e}"))
    }

    /// The mute record for `player_id`, if any.
    #[must_use]
    pub fn get(&self, player_id: &Uuid) -> Option<&ServerMute> {
        self.mutes.get(player_id)
    }

    /// Whether `player_id` currently has an active mute — the flag `relay_audio`
    /// and `voice_player_info` both consult.
    #[must_use]
    pub fn is_muted(&self, player_id: &Uuid, now_ms: u64) -> bool {
        self.mutes
            .get(player_id)
            .is_some_and(|mute| mute.is_active(now_ms))
    }

    /// Records (or replaces) the mute for `player_id`, returning the previous
    /// value when one was already present.
    ///
    /// `muted_to_ms` is the absolute epoch-millisecond expiry, mirroring upstream's
    /// `ServerMuteInfo.mutedToTime`; pass `0` for a permanent mute. Relative
    /// durations are resolved by the caller (the command layer adds them to the
    /// current clock) so a `timestamp` duration needs no special casing here.
    pub fn mutate(
        &mut self,
        player_id: Uuid,
        muted_by: Option<Uuid>,
        muted_to_ms: u64,
        reason: Option<String>,
        now_ms: u64,
    ) -> Option<ServerMute> {
        self.mutes.insert(
            player_id,
            ServerMute {
                player_id,
                muted_by,
                muted_at_ms: now_ms,
                muted_to_ms,
                reason,
            },
        )
    }

    /// Removes a mute, returning the previous record when it existed.
    pub fn unmute(&mut self, player_id: &Uuid) -> Option<ServerMute> {
        self.mutes.remove(player_id)
    }

    /// Drops entries that have expired at `now_ms`. Returns the players it freed.
    pub fn purge_owned(&mut self, now_ms: u64) -> Vec<Uuid> {
        let expired: Vec<Uuid> = self
            .mutes
            .iter()
            .filter(|(_, mute)| !mute.is_active(now_ms))
            .map(|(id, _)| *id)
            .collect();
        for id in &expired {
            self.mutes.remove(id);
        }
        expired
    }

    /// All non-expired mutes, ordered by player id.
    pub fn active(&self, now_ms: u64) -> Vec<&ServerMute> {
        self.mutes
            .values()
            .filter(|mute| mute.is_active(now_ms))
            .collect()
    }

    /// Number of stored records (expired or not).
    #[must_use]
    pub fn len(&self) -> usize {
        self.mutes.len()
    }

    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.mutes.is_empty()
    }
}

/// The process-wide mute store.
///
/// This is server state the commands and the protocol both touch, so it lives in a
/// `OnceLock` like the socket runtime rather than inside `VoiceServer`. A host test
/// that never calls [`init`] simply sees an empty store, which is exactly the
/// "nobody is muted" default.
static STORE: OnceLock<Mutex<MuteStore>> = OnceLock::new();

/// Locks the global mute store, creating it empty on first use.
///
/// Poisoning is unrecoverable by design (a panicked holder leaves no valid state),
/// so a poisoned lock is reset rather than propagated.
pub fn store() -> MutexGuard<'static, MuteStore> {
    STORE
        .get_or_init(|| Mutex::new(MuteStore::new()))
        .lock()
        .unwrap_or_else(|poisoned| poisoned.into_inner())
}

/// Loads `mutes.toml` from the plugin data folder into the global store.
///
/// An absent file is a fresh server (no mutes); an unreadable or malformed one
/// degrades to an empty store rather than failing the plugin load, and is reported
/// so the operator can fix the file while the server keeps running.
pub fn init(folder: &str) {
    match std::fs::read_to_string(format!("{folder}/{MUTE_FILE}")) {
        Ok(text) => match MuteStore::load(&text) {
            Ok(loaded) => {
                tracing::debug!(path = %format!("{folder}/{MUTE_FILE}"), mutes = loaded.len(), "loaded server mutes");
                *store() = loaded;
            }
            Err(error) => {
                tracing::warn!(%error, path = %format!("{folder}/{MUTE_FILE}"), "mutes.toml does not parse; starting with an empty mute table");
            }
        },
        Err(_) => {
            // No file yet — the first mute creates one.
            tracing::debug!(path = %format!("{folder}/{MUTE_FILE}"), "no mute table yet; starting empty");
        }
    }
}

/// Persists the global store to `folder/mutes.toml`, dropping expired entries.
pub fn save(folder: &str) -> Result<(), String> {
    store().save(folder)
}

/// Whether `player_id` is server-muted right now (unexpired entry in the store).
#[must_use]
pub fn is_muted(player_id: &Uuid, now_ms: u64) -> bool {
    store().is_muted(player_id, now_ms)
}

/// Unmutes every player whose temporary mute has expired at `now_ms`, returning
/// their ids. Mirrors the periodic `tick()` in upstream `VoiceMuteManager`: the
/// record is actually removed (not merely ignored), so `tick.rs` can broadcast
/// the changed mute state and announce the lift under the `notify_unmuted` flag.
#[must_use]
pub fn expire_due(now_ms: u64) -> Vec<Uuid> {
    store().purge_owned(now_ms)
}

/// Parses a `/vmute` duration argument into the absolute mute expiry, mirroring
/// upstream `MuteDurationType.parse`:
///
/// * `"permanent"` (exactly, like upstream) → `Ok(None)` — the mute never expires.
/// * `<digits>` with an optional unit `s`, `m`, `h`, `d` or `w` → relative to
///   `now_ms`: `Ok(Some(now_ms + amount))`; bare digits are seconds.
/// * `<digits>u` → `Ok(Some(amount * 1000))`: the amount is a Unix-seconds
///   timestamp, rejected when it is not strictly in the future (upstream's
///   `TIMESTAMP_IN_PAST`).
/// * anything else, a non-positive amount, or an overflowing computation → `Err`,
///   matching upstream's `INVALID_DURATION` on an `ArithmeticException`.
///
/// The result is always an absolute epoch-millisecond expiry because
/// [`MuteStore::mutate`] stores absolute times; a timestamp unit therefore needs
/// no special casing in the store.
pub fn parse_mute_duration(input: &str, now_ms: u64) -> Result<Option<u64>, String> {
    if input == "permanent" {
        return Ok(None);
    }

    // Upstream regex `^([0-9]+)([mhdwsu])?$`; `[0-9]+` admits leading zeroes but
    // the amount must be positive.
    let (digits, unit) = match input.bytes().last() {
        Some(unit @ (b'm' | b'h' | b'd' | b'w' | b'u' | b's')) => (&input[..input.len() - 1], unit),
        _ => (input, b's'),
    };
    if digits.is_empty() || !digits.bytes().all(|byte| byte.is_ascii_digit()) {
        return Err(invalid_duration(input));
    }
    let amount = digits.parse::<u64>().map_err(|_| invalid_duration(input))?;
    if amount == 0 {
        return Err(invalid_duration(input));
    }

    let unit_millis = match unit {
        b'm' => 60_000,
        b'h' => 3_600_000,
        b'd' => 86_400_000,
        b'w' => 604_800_000,
        _ => 1_000, // bare digits or `s`
    };

    if unit == b'u' {
        // The digits are already a Unix-seconds timestamp; ×1000 is the mutation
        // to epoch millis. Overflow throws upstream (`Math.multiplyExact`).
        let timestamp = amount
            .checked_mul(1_000)
            .ok_or_else(|| invalid_duration(input))?;
        if timestamp <= now_ms {
            return Err(format!("timestamp '{input}' is in the past"));
        }
        Ok(Some(timestamp))
    } else {
        let duration = amount
            .checked_mul(unit_millis)
            .ok_or_else(|| invalid_duration(input))?;
        let expiry = now_ms
            .checked_add(duration)
            .ok_or_else(|| invalid_duration(input))?;
        Ok(Some(expiry))
    }
}

fn invalid_duration(input: &str) -> String {
    format!(
        "invalid duration '{input}': expected <amount>[s|m|h|d|w], a <seconds>u timestamp, or 'permanent'"
    )
}

/// The chat line a freshly muted player is told, resolved to plain text.
///
/// Upstream sends `McTextComponent.translatable("pv.mutes.temporarily_muted", ...)`
/// and lets the *mod* resolve it; a vanilla Pumpkin client has no `[server.pv.mutes]`
/// scope in its own lang file, so this server resolves the wording itself. The keys
/// and the `en_us.toml` strings are mirrored verbatim (see the compacted history:
/// `temporarily_muted` / `permanently_muted` / `empty_reason`).
///
/// `duration_text` is `format_mute_duration`'s output for a temporary mute and `None`
/// for a permanent one; `reason` is the operator's free text, or `None` for the
/// "not specified" default.
#[must_use]
pub fn muted_notice(duration_text: Option<&str>, reason: Option<&str>) -> String {
    let reason = reason_text(reason);
    match duration_text {
        Some(duration) => format!("You've been muted {duration}. Reason: {reason}"),
        None => format!("You've been permanently muted. Reason: {reason}"),
    }
}

/// The chat line a player is told when a mute lifts, resolved to plain text
/// (`pv.mutes.unmuted` in `en_us.toml`).
#[must_use]
pub fn unmuted_notice() -> String {
    "You've been unmuted".to_string()
}

/// Renders a raw `/vmute` duration argument the way upstream's
/// `MuteDurationUnit.translate` does — `pv.mutes.durations.*` with the *raw*
/// operator amount: `"5m"` → `"for 5 min"`. `"permanent"` and anything
/// unparsable return `None`, so the caller falls back to the permanent line or
/// its own remaining-seconds text.
#[must_use]
pub fn format_mute_duration(input: &str) -> Option<String> {
    if input == "permanent" {
        return None;
    }
    let (digits, unit) = match input.bytes().last() {
        Some(unit @ (b's' | b'm' | b'h' | b'd' | b'w' | b'u')) => (&input[..input.len() - 1], unit),
        _ => (input, b's'),
    };
    if digits.is_empty() || !digits.bytes().all(|byte| byte.is_ascii_digit()) {
        return None;
    }
    let amount = digits.parse::<u64>().ok()?;
    let label = match unit {
        b's' => "sec",
        b'm' => "min",
        b'h' => "h",
        b'd' => "d",
        b'w' => "w",
        // Upstream translates a TIMESTAMP mute with the seconds key and the raw
        // unix-seconds amount, which is quirky but faithful.
        b'u' => "sec",
        _ => return None,
    };
    Some(format!("for {amount} {label}"))
}

/// `pv.mutes.empty_reason` — "not specified" — applied when no reason was given.
fn reason_text(reason: Option<&str>) -> String {
    reason.unwrap_or("not specified").to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn uuid(n: u128) -> Uuid {
        Uuid::from_u128(n)
    }

    fn sample_store(now: u64) -> MuteStore {
        let mut store = MuteStore::new();
        store.mutate(uuid(1), Some(uuid(9)), 0, Some("spamming".to_string()), now);
        store.mutate(uuid(2), None, now + 30 * 60_000, None, now);
        store
    }

    #[test]
    fn round_trips_through_toml() {
        let store = sample_store(1_700_000_000_000);
        let back = MuteStore::load(&store.to_toml()).expect("parse");
        assert_eq!(back, store);
    }

    #[test]
    fn toml_is_flat_and_human_readable() {
        let store = sample_store(1_700_000_000_000);
        let toml = store.to_toml();
        assert!(toml.contains("mutes."), "keys carry the player uuid");
        assert!(
            toml.contains("muted_to_ms = 0"),
            "permanent mutes are explicit"
        );
        assert!(toml.contains("reason = \"spamming\""));
    }

    #[test]
    fn load_tolerates_comments_unknown_keys_and_bad_entries() {
        let good = sample_store(1_700_000_000_000);
        let good_toml = good.to_toml();
        let toml = format!(
            "# a comment\n\
             {good_toml}\n\
             mutes.not-a-uuid.muted_at_ms = 1\n\
             mutes.{}.muted_at_ms = not-a-number\n\
             future_key = \"ignored\"",
            uuid(99)
        );
        let parsed = MuteStore::load(&toml).expect("parse");
        assert_eq!(parsed, good);
    }

    #[test]
    fn temporary_mute_expires_and_is_purged() {
        let mut store = MuteStore::new();
        let now = 1_700_000_000_000;
        store.mutate(uuid(1), None, now + 60_000, None, now); // lifts at now + 60_000
        assert!(store.is_muted(&uuid(1), now));
        assert!(store.is_muted(&uuid(1), now + 59_999));
        assert!(!store.is_muted(&uuid(1), now + 60_000));

        let freed = store.purge_owned(now + 60_000);
        assert_eq!(freed, vec![uuid(1)]);
        assert!(store.is_empty());
    }

    #[test]
    fn permanent_mute_never_expires() {
        let store = sample_store(1_700_000_000_000);
        assert!(store.is_muted(&uuid(1), u64::MAX));
        assert!(
            !store.is_muted(&uuid(2), u64::MAX),
            "temporary mute still lifts"
        );
    }

    #[test]
    fn unmute_removes_and_returns_the_previous_record() {
        let mut store = sample_store(1_700_000_000_000);
        let previous = store.unmute(&uuid(1)).expect("a record");
        assert_eq!(previous.player_id, uuid(1));
        assert_eq!(previous.muted_by, Some(uuid(9)));
        assert!(store.unmute(&uuid(1)).is_none());
        assert!(!store.is_muted(&uuid(1), 1_700_000_000_000));
    }

    #[test]
    fn active_lists_only_live_mutes_in_order() {
        let mut store = sample_store(1_700_000_000_000);
        store.mutate(uuid(3), None, 0, None, 1_700_000_000_000);
        let live = store.active(1_700_000_000_500);
        assert_eq!(
            live.iter().map(|m| m.player_id).collect::<Vec<_>>(),
            vec![uuid(1), uuid(2), uuid(3)],
            "BTreeMap order"
        );
        let after = store.active(1_700_000_000_000 + 30 * 60_000);
        assert_eq!(
            after.iter().map(|m| m.player_id).collect::<Vec<_>>(),
            vec![uuid(1), uuid(3)],
            "the 30-minute mute dropped out"
        );
    }

    #[test]
    fn describe_renders_permanent_and_remaining() {
        let store = sample_store(1_700_000_000_000);
        assert_eq!(
            store.get(&uuid(1)).expect("mute").describe(0),
            "permanently"
        );
        assert_eq!(
            store
                .get(&uuid(2))
                .expect("mute")
                .describe(1_700_000_000_000),
            "for 1800s"
        );
    }

    #[test]
    fn parse_duration_accepts_permanent_and_relative_units() {
        let now = 1_700_000_000_000;
        assert_eq!(parse_mute_duration("permanent", now), Ok(None));
        assert_eq!(parse_mute_duration("5s", now), Ok(Some(now + 5_000)));
        assert_eq!(parse_mute_duration("5", now), Ok(Some(now + 5_000)));
        assert_eq!(parse_mute_duration("2m", now), Ok(Some(now + 120_000)));
        assert_eq!(parse_mute_duration("2h", now), Ok(Some(now + 7_200_000)));
        assert_eq!(parse_mute_duration("2d", now), Ok(Some(now + 172_800_000)));
        assert_eq!(
            parse_mute_duration("2w", now),
            Ok(Some(now + 1_209_600_000))
        );
        assert_eq!(parse_mute_duration("007m", now), Ok(Some(now + 420_000)));
        assert_eq!(
            parse_mute_duration("1700000100u", now),
            Ok(Some(1_700_000_100_000)),
            "a `u` amount is a Unix-seconds timestamp"
        );
    }

    #[test]
    fn parse_duration_rejects_bad_input_and_past_timestamps() {
        let now = 1_700_000_000_000;
        for bad in [
            "",
            "0",
            "0s",
            "-5s",
            "5x",
            "s",
            "min",
            "Permanent",
            "1.5m",
            "1h30m",
            "m",
        ] {
            assert!(
                parse_mute_duration(bad, now).is_err(),
                "{bad:?} should be invalid"
            );
        }
        assert!(
            parse_mute_duration("1700000000u", now).is_err(),
            "a timestamp equal to now is not strictly in the future"
        );
        assert!(
            parse_mute_duration("999u", now).is_err(),
            "a past timestamp is rejected"
        );
        assert!(
            parse_mute_duration("18446744073709551s", now).is_err(),
            "overflowing the clock is invalid rather than wrapping"
        );
    }

    #[test]
    fn format_duration_renders_the_raw_amount_like_upstream() {
        assert_eq!(format_mute_duration("5s").as_deref(), Some("for 5 sec"));
        assert_eq!(format_mute_duration("5m").as_deref(), Some("for 5 min"));
        assert_eq!(format_mute_duration("2h").as_deref(), Some("for 2 h"));
        assert_eq!(format_mute_duration("3d").as_deref(), Some("for 3 d"));
        assert_eq!(format_mute_duration("1w").as_deref(), Some("for 1 w"));
        assert_eq!(format_mute_duration("15").as_deref(), Some("for 15 sec"));
        assert_eq!(
            format_mute_duration("1700000100u").as_deref(),
            Some("for 1700000100 sec"),
            "a `u` timestamp keeps its raw unix-seconds amount, like `MuteDurationUnit.translate`"
        );
        assert_eq!(format_mute_duration("permanent"), None);
        assert_eq!(format_mute_duration(""), None);
        assert_eq!(format_mute_duration("1.5m"), None);
        assert_eq!(format_mute_duration("min"), None);
    }

    #[test]
    fn notices_use_the_upstream_en_us_wording() {
        assert_eq!(
            muted_notice(Some("for 5 min"), Some("spamming")),
            "You've been muted for 5 min. Reason: spamming"
        );
        assert_eq!(
            muted_notice(Some("for 5 min"), None),
            "You've been muted for 5 min. Reason: not specified"
        );
        assert_eq!(
            muted_notice(None, Some("spamming")),
            "You've been permanently muted. Reason: spamming"
        );
        assert_eq!(
            muted_notice(None, None),
            "You've been permanently muted. Reason: not specified"
        );
        assert_eq!(unmuted_notice(), "You've been unmuted");
    }

    #[test]
    fn expire_due_lifts_only_expired_mutes_from_the_global_store() {
        *store() = MuteStore::new();
        let now = 1_700_000_000_000;
        store().mutate(uuid(1), None, now + 60_000, None, now); // lifts at now + 60_000
        store().mutate(uuid(2), None, 0, None, now); // permanent
        assert_eq!(expire_due(now + 60_000), vec![uuid(1)]);
        assert!(!store().is_muted(&uuid(1), now + 60_000));
        assert!(store().is_muted(&uuid(2), u64::MAX));
        *store() = MuteStore::new();
    }
}
