# SPDX-License-Identifier: LGPL-3.0-only
# The client-scope half of plasmoapp/plasmo-voice-crowdin @ pv : pl_PL/server.toml
# (upstream reads this in VoiceServerLanguages.getClientLanguage).
[client.pv.activation]
proximity = "Zbliżeniowy"
